import type { GlobalBeforeChangeHook } from "payload";

type ThemeColors = {
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  muted: string;
  mutedForeground: string;
  primary: string;
  primaryForeground: string;
  accent: string;
  accentForeground: string;
  secondary: string;
  border: string;
  input: string;
  ring: string;
  success: string;
  warning: string;
  destructive: string;
};

type Preset = {
  light: ThemeColors;
  dark: ThemeColors;
  fontHeading: string;
  fontBody: string;
  fontMono: string;
  radius: string;
  buttonStyle: string;
  shadow: string;
};

export const BRAND_PRESETS: Record<string, Preset> = {
  modern: {
    light: {
      background: "#ffffff",
      foreground: "#0a0a0a",
      card: "#ffffff",
      cardForeground: "#0a0a0a",
      muted: "#f5f5f5",
      mutedForeground: "#737373",
      primary: "#6366f1",
      primaryForeground: "#ffffff",
      accent: "#22d3ee",
      accentForeground: "#0a0a0a",
      secondary: "#a855f7",
      border: "#e5e5e5",
      input: "#e5e5e5",
      ring: "#6366f1",
      success: "#10b981",
      warning: "#f59e0b",
      destructive: "#ef4444",
    },
    dark: {
      background: "#0a0a0a",
      foreground: "#fafafa",
      card: "#0f0f0f",
      cardForeground: "#fafafa",
      muted: "#1a1a1a",
      mutedForeground: "#a3a3a3",
      primary: "#818cf8",
      primaryForeground: "#0a0a0a",
      accent: "#67e8f9",
      accentForeground: "#0a0a0a",
      secondary: "#c084fc",
      border: "#262626",
      input: "#262626",
      ring: "#818cf8",
      success: "#34d399",
      warning: "#fbbf24",
      destructive: "#f87171",
    },
    fontHeading: "Inter",
    fontBody: "Inter",
    fontMono: "JetBrains Mono",
    radius: "md",
    buttonStyle: "fill",
    shadow: "sm",
  },
  editorial: {
    light: {
      background: "#fefefe",
      foreground: "#1e293b",
      card: "#ffffff",
      cardForeground: "#1e293b",
      muted: "#f1f5f9",
      mutedForeground: "#64748b",
      primary: "#0f172a",
      primaryForeground: "#fefefe",
      accent: "#f59e0b",
      accentForeground: "#0a0a0a",
      secondary: "#475569",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#0f172a",
      success: "#059669",
      warning: "#d97706",
      destructive: "#dc2626",
    },
    dark: {
      background: "#0f172a",
      foreground: "#e2e8f0",
      card: "#1e293b",
      cardForeground: "#e2e8f0",
      muted: "#1e293b",
      mutedForeground: "#94a3b8",
      primary: "#fefefe",
      primaryForeground: "#0f172a",
      accent: "#fbbf24",
      accentForeground: "#0f172a",
      secondary: "#cbd5e1",
      border: "#334155",
      input: "#334155",
      ring: "#fbbf24",
      success: "#34d399",
      warning: "#fbbf24",
      destructive: "#f87171",
    },
    fontHeading: "Lora",
    fontBody: "Source Serif Pro",
    fontMono: "IBM Plex Mono",
    radius: "sm",
    buttonStyle: "outline",
    shadow: "none",
  },
  bold: {
    light: {
      background: "#ffffff",
      foreground: "#000000",
      card: "#ffffff",
      cardForeground: "#000000",
      muted: "#fafafa",
      mutedForeground: "#525252",
      primary: "#000000",
      primaryForeground: "#ffffff",
      accent: "#a3e635",
      accentForeground: "#000000",
      secondary: "#f43f5e",
      border: "#000000",
      input: "#171717",
      ring: "#a3e635",
      success: "#22c55e",
      warning: "#eab308",
      destructive: "#dc2626",
    },
    dark: {
      background: "#000000",
      foreground: "#fafafa",
      card: "#0a0a0a",
      cardForeground: "#fafafa",
      muted: "#171717",
      mutedForeground: "#a3a3a3",
      primary: "#fafafa",
      primaryForeground: "#000000",
      accent: "#bef264",
      accentForeground: "#000000",
      secondary: "#fb7185",
      border: "#fafafa",
      input: "#262626",
      ring: "#bef264",
      success: "#4ade80",
      warning: "#facc15",
      destructive: "#f87171",
    },
    fontHeading: "Space Grotesk",
    fontBody: "Space Grotesk",
    fontMono: "Geist Mono",
    radius: "lg",
    buttonStyle: "fill",
    shadow: "md",
  },
  minimal: {
    light: {
      background: "#ffffff",
      foreground: "#0a0a0a",
      card: "#ffffff",
      cardForeground: "#0a0a0a",
      muted: "#fafafa",
      mutedForeground: "#737373",
      primary: "#171717",
      primaryForeground: "#ffffff",
      accent: "#737373",
      accentForeground: "#ffffff",
      secondary: "#a3a3a3",
      border: "#e5e5e5",
      input: "#e5e5e5",
      ring: "#171717",
      success: "#16a34a",
      warning: "#ca8a04",
      destructive: "#b91c1c",
    },
    dark: {
      background: "#0a0a0a",
      foreground: "#fafafa",
      card: "#171717",
      cardForeground: "#fafafa",
      muted: "#171717",
      mutedForeground: "#a3a3a3",
      primary: "#fafafa",
      primaryForeground: "#0a0a0a",
      accent: "#a3a3a3",
      accentForeground: "#0a0a0a",
      secondary: "#737373",
      border: "#262626",
      input: "#262626",
      ring: "#fafafa",
      success: "#22c55e",
      warning: "#eab308",
      destructive: "#ef4444",
    },
    fontHeading: "Geist",
    fontBody: "Geist",
    fontMono: "Geist Mono",
    radius: "none",
    buttonStyle: "outline",
    shadow: "none",
  },
  warm: {
    light: {
      background: "#fefcf9",
      foreground: "#1c1917",
      card: "#ffffff",
      cardForeground: "#1c1917",
      muted: "#f5f3ee",
      mutedForeground: "#78716c",
      primary: "#c2410c",
      primaryForeground: "#ffffff",
      accent: "#f59e0b",
      accentForeground: "#1c1917",
      secondary: "#92400e",
      border: "#e7e5e4",
      input: "#e7e5e4",
      ring: "#c2410c",
      success: "#65a30d",
      warning: "#ea580c",
      destructive: "#b91c1c",
    },
    dark: {
      background: "#1c1917",
      foreground: "#fafaf9",
      card: "#292524",
      cardForeground: "#fafaf9",
      muted: "#292524",
      mutedForeground: "#a8a29e",
      primary: "#fb923c",
      primaryForeground: "#1c1917",
      accent: "#fbbf24",
      accentForeground: "#1c1917",
      secondary: "#d97706",
      border: "#44403c",
      input: "#44403c",
      ring: "#fb923c",
      success: "#84cc16",
      warning: "#f97316",
      destructive: "#f87171",
    },
    fontHeading: "Manrope",
    fontBody: "Manrope",
    fontMono: "JetBrains Mono",
    radius: "lg",
    buttonStyle: "soft",
    shadow: "md",
  },
  premium: {
    light: {
      background: "#ffffff",
      foreground: "#1e293b",
      card: "#ffffff",
      cardForeground: "#1e293b",
      muted: "#f8fafc",
      mutedForeground: "#64748b",
      primary: "#1e3a8a",
      primaryForeground: "#ffffff",
      accent: "#ca8a04",
      accentForeground: "#ffffff",
      secondary: "#0c4a6e",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#1e3a8a",
      success: "#15803d",
      warning: "#a16207",
      destructive: "#991b1b",
    },
    dark: {
      background: "#0f172a",
      foreground: "#f8fafc",
      card: "#1e293b",
      cardForeground: "#f8fafc",
      muted: "#1e293b",
      mutedForeground: "#94a3b8",
      primary: "#93c5fd",
      primaryForeground: "#0f172a",
      accent: "#fbbf24",
      accentForeground: "#0f172a",
      secondary: "#7dd3fc",
      border: "#334155",
      input: "#334155",
      ring: "#93c5fd",
      success: "#4ade80",
      warning: "#fbbf24",
      destructive: "#f87171",
    },
    fontHeading: "Playfair Display",
    fontBody: "Inter",
    fontMono: "IBM Plex Mono",
    radius: "sm",
    buttonStyle: "fill",
    shadow: "lg",
  },
  tech: {
    light: {
      background: "#ffffff",
      foreground: "#0a0a0a",
      card: "#fafafa",
      cardForeground: "#0a0a0a",
      muted: "#f5f5f5",
      mutedForeground: "#525252",
      primary: "#06b6d4",
      primaryForeground: "#ffffff",
      accent: "#d946ef",
      accentForeground: "#ffffff",
      secondary: "#0891b2",
      border: "#e5e5e5",
      input: "#e5e5e5",
      ring: "#06b6d4",
      success: "#10b981",
      warning: "#f59e0b",
      destructive: "#ef4444",
    },
    dark: {
      background: "#0a0a0a",
      foreground: "#fafafa",
      card: "#0f0f0f",
      cardForeground: "#fafafa",
      muted: "#1a1a1a",
      mutedForeground: "#a3a3a3",
      primary: "#22d3ee",
      primaryForeground: "#0a0a0a",
      accent: "#e879f9",
      accentForeground: "#0a0a0a",
      secondary: "#67e8f9",
      border: "#262626",
      input: "#262626",
      ring: "#22d3ee",
      success: "#34d399",
      warning: "#fbbf24",
      destructive: "#f87171",
    },
    fontHeading: "Space Grotesk",
    fontBody: "Inter",
    fontMono: "JetBrains Mono",
    radius: "md",
    buttonStyle: "fill",
    shadow: "md",
  },
};

/**
 * Hook beforeChange : si l'utilisateur a sélectionné un scénario ≠ 'custom',
 * remplace TOUTES les couleurs (light + dark) + typographie + radius + buttonStyle + shadow,
 * puis remet `preset` à 'custom' pour que le prochain save n'écrase pas ses ajustements.
 */
export const applyBrandPreset: GlobalBeforeChangeHook = ({ data }) => {
  const preset = data.preset as string | undefined;
  if (!preset || preset === "custom") return data;
  const p = BRAND_PRESETS[preset];
  if (!p) return data;
  return {
    ...data,
    // Light theme (top-level fields)
    ...p.light,
    // Dark theme (nested under `dark`)
    dark: { ...p.dark },
    // Composants & typo
    fontHeading: p.fontHeading,
    fontBody: p.fontBody,
    fontMono: p.fontMono,
    radius: p.radius,
    buttonStyle: p.buttonStyle,
    shadow: p.shadow,
    preset: "custom",
  };
};
