import { MigrateUpArgs, MigrateDownArgs, sql } from "@payloadcms/db-postgres";

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_hero_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_hero_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_features_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_features_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_cta_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_cta_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_hero_2_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_hero_2_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_features_2_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_features_2_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_cta_2_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_cta_2_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_2_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_2_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_logo_cloud_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_logo_cloud_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_pricing_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_pricing_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_testimonials_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_testimonials_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_faq_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_faq_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_stats_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_stats_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_group_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_group_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_form_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_form_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_newsletter_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_newsletter_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_features_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_features_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_2_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_2_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_features_2_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_features_2_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_2_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_2_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_2_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_2_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_logo_cloud_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_logo_cloud_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_pricing_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_pricing_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_testimonials_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_testimonials_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_faq_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_faq_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_stats_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_stats_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_group_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_group_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_form_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_form_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_newsletter_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_newsletter_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_hero_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_hero_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_features_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_features_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_cta_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_cta_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_rich_text_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_rich_text_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_hero_2_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_hero_2_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_features_2_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_features_2_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_cta_2_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_cta_2_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_rich_text_2_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_rich_text_2_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_logo_cloud_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_logo_cloud_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_pricing_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_pricing_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_testimonials_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_testimonials_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_faq_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_faq_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_stats_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_stats_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_group_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_group_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_newsletter_appearance_padding_top" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TYPE "public"."enum_snippets_blocks_newsletter_appearance_padding_bottom" AS ENUM('none', 'sm', 'md', 'lg');
  CREATE TABLE "posts_tags" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"tag" varchar
  );
  
  CREATE TABLE "_posts_v_version_tags" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"tag" varchar,
  	"_uuid" varchar
  );
  
  ALTER TABLE "users" ADD COLUMN "slug" varchar;
  ALTER TABLE "users" ADD COLUMN "bio" varchar;
  ALTER TABLE "users" ADD COLUMN "avatar_id" integer;
  ALTER TABLE "users" ADD COLUMN "socials_website" varchar;
  ALTER TABLE "users" ADD COLUMN "socials_twitter" varchar;
  ALTER TABLE "users" ADD COLUMN "socials_linkedin" varchar;
  ALTER TABLE "users" ADD COLUMN "socials_github" varchar;
  ALTER TABLE "posts" ADD COLUMN "noindex" boolean;
  ALTER TABLE "posts" ADD COLUMN "canonical" varchar;
  ALTER TABLE "_posts_v" ADD COLUMN "version_noindex" boolean;
  ALTER TABLE "_posts_v" ADD COLUMN "version_canonical" varchar;
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_hero_appearance_padding_top";
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_hero_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_features" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_features_appearance_padding_top";
  ALTER TABLE "pages_blocks_features" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_features_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_cta_appearance_padding_top";
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_cta_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_rich_text_appearance_padding_top";
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_rich_text_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_hero_2" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_hero_2_appearance_padding_top";
  ALTER TABLE "pages_blocks_hero_2" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_hero_2_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_features_2" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_features_2_appearance_padding_top";
  ALTER TABLE "pages_blocks_features_2" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_features_2_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_cta_2" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_cta_2_appearance_padding_top";
  ALTER TABLE "pages_blocks_cta_2" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_cta_2_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_rich_text_2" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_rich_text_2_appearance_padding_top";
  ALTER TABLE "pages_blocks_rich_text_2" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_rich_text_2_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_logo_cloud" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_logo_cloud_appearance_padding_top";
  ALTER TABLE "pages_blocks_logo_cloud" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_logo_cloud_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_pricing" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_pricing_appearance_padding_top";
  ALTER TABLE "pages_blocks_pricing" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_pricing_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_testimonials_appearance_padding_top";
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_testimonials_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_faq_appearance_padding_top";
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_faq_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_stats_appearance_padding_top";
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_stats_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_group" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_group_appearance_padding_top";
  ALTER TABLE "pages_blocks_group" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_group_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_form" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_form_appearance_padding_top";
  ALTER TABLE "pages_blocks_form" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_form_appearance_padding_bottom";
  ALTER TABLE "pages_blocks_newsletter" ADD COLUMN "appearance_padding_top" "enum_pages_blocks_newsletter_appearance_padding_top";
  ALTER TABLE "pages_blocks_newsletter" ADD COLUMN "appearance_padding_bottom" "enum_pages_blocks_newsletter_appearance_padding_bottom";
  ALTER TABLE "pages" ADD COLUMN "noindex" boolean;
  ALTER TABLE "pages" ADD COLUMN "canonical" varchar;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_hero_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_hero_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_features_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_features_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_cta_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_cta_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_rich_text_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_rich_text_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_hero_2" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_hero_2_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_hero_2" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_hero_2_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_features_2" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_features_2_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_features_2" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_features_2_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_cta_2" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_cta_2_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_cta_2" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_cta_2_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_rich_text_2" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_rich_text_2_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_rich_text_2" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_rich_text_2_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_logo_cloud_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_logo_cloud_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_pricing" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_pricing_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_pricing" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_pricing_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_testimonials_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_testimonials_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_faq_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_faq_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_stats_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_stats_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_group" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_group_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_group" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_group_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_form" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_form_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_form" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_form_appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_newsletter" ADD COLUMN "appearance_padding_top" "enum__pages_v_blocks_newsletter_appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_newsletter" ADD COLUMN "appearance_padding_bottom" "enum__pages_v_blocks_newsletter_appearance_padding_bottom";
  ALTER TABLE "_pages_v" ADD COLUMN "version_noindex" boolean;
  ALTER TABLE "_pages_v" ADD COLUMN "version_canonical" varchar;
  ALTER TABLE "snippets_blocks_hero" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_hero_appearance_padding_top";
  ALTER TABLE "snippets_blocks_hero" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_hero_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_features" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_features_appearance_padding_top";
  ALTER TABLE "snippets_blocks_features" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_features_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_cta" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_cta_appearance_padding_top";
  ALTER TABLE "snippets_blocks_cta" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_cta_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_rich_text" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_rich_text_appearance_padding_top";
  ALTER TABLE "snippets_blocks_rich_text" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_rich_text_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_hero_2" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_hero_2_appearance_padding_top";
  ALTER TABLE "snippets_blocks_hero_2" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_hero_2_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_features_2" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_features_2_appearance_padding_top";
  ALTER TABLE "snippets_blocks_features_2" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_features_2_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_cta_2" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_cta_2_appearance_padding_top";
  ALTER TABLE "snippets_blocks_cta_2" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_cta_2_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_rich_text_2" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_rich_text_2_appearance_padding_top";
  ALTER TABLE "snippets_blocks_rich_text_2" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_rich_text_2_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_logo_cloud" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_logo_cloud_appearance_padding_top";
  ALTER TABLE "snippets_blocks_logo_cloud" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_logo_cloud_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_pricing" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_pricing_appearance_padding_top";
  ALTER TABLE "snippets_blocks_pricing" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_pricing_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_testimonials" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_testimonials_appearance_padding_top";
  ALTER TABLE "snippets_blocks_testimonials" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_testimonials_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_faq" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_faq_appearance_padding_top";
  ALTER TABLE "snippets_blocks_faq" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_faq_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_stats" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_stats_appearance_padding_top";
  ALTER TABLE "snippets_blocks_stats" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_stats_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_group" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_group_appearance_padding_top";
  ALTER TABLE "snippets_blocks_group" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_group_appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_newsletter" ADD COLUMN "appearance_padding_top" "enum_snippets_blocks_newsletter_appearance_padding_top";
  ALTER TABLE "snippets_blocks_newsletter" ADD COLUMN "appearance_padding_bottom" "enum_snippets_blocks_newsletter_appearance_padding_bottom";
  ALTER TABLE "posts_tags" ADD CONSTRAINT "posts_tags_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_posts_v_version_tags" ADD CONSTRAINT "_posts_v_version_tags_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_posts_v"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "posts_tags_order_idx" ON "posts_tags" USING btree ("_order");
  CREATE INDEX "posts_tags_parent_id_idx" ON "posts_tags" USING btree ("_parent_id");
  CREATE INDEX "_posts_v_version_tags_order_idx" ON "_posts_v_version_tags" USING btree ("_order");
  CREATE INDEX "_posts_v_version_tags_parent_id_idx" ON "_posts_v_version_tags" USING btree ("_parent_id");
  ALTER TABLE "users" ADD CONSTRAINT "users_avatar_id_media_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE UNIQUE INDEX "users_slug_idx" ON "users" USING btree ("slug");
  CREATE INDEX "users_avatar_idx" ON "users" USING btree ("avatar_id");`);
}

export async function down({
  db,
  payload,
  req,
}: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "posts_tags" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_posts_v_version_tags" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "posts_tags" CASCADE;
  DROP TABLE "_posts_v_version_tags" CASCADE;
  ALTER TABLE "users" DROP CONSTRAINT "users_avatar_id_media_id_fk";
  
  DROP INDEX "users_slug_idx";
  DROP INDEX "users_avatar_idx";
  ALTER TABLE "users" DROP COLUMN "slug";
  ALTER TABLE "users" DROP COLUMN "bio";
  ALTER TABLE "users" DROP COLUMN "avatar_id";
  ALTER TABLE "users" DROP COLUMN "socials_website";
  ALTER TABLE "users" DROP COLUMN "socials_twitter";
  ALTER TABLE "users" DROP COLUMN "socials_linkedin";
  ALTER TABLE "users" DROP COLUMN "socials_github";
  ALTER TABLE "posts" DROP COLUMN "noindex";
  ALTER TABLE "posts" DROP COLUMN "canonical";
  ALTER TABLE "_posts_v" DROP COLUMN "version_noindex";
  ALTER TABLE "_posts_v" DROP COLUMN "version_canonical";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_hero_2" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_hero_2" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_features_2" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_features_2" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_cta_2" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_cta_2" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_rich_text_2" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_rich_text_2" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_logo_cloud" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_logo_cloud" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_pricing" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_pricing" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_group" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_group" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_form" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_form" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages_blocks_newsletter" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "pages_blocks_newsletter" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "pages" DROP COLUMN "noindex";
  ALTER TABLE "pages" DROP COLUMN "canonical";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_hero_2" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_hero_2" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_features_2" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_features_2" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_cta_2" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_cta_2" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_rich_text_2" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_rich_text_2" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_pricing" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_pricing" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_group" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_group" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_form" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_form" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v_blocks_newsletter" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_pages_v_blocks_newsletter" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_pages_v" DROP COLUMN "version_noindex";
  ALTER TABLE "_pages_v" DROP COLUMN "version_canonical";
  ALTER TABLE "snippets_blocks_hero" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_hero" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_features" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_features" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_cta" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_cta" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_rich_text" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_rich_text" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_hero_2" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_hero_2" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_features_2" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_features_2" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_cta_2" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_cta_2" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_rich_text_2" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_rich_text_2" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_logo_cloud" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_logo_cloud" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_pricing" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_pricing" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_testimonials" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_testimonials" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_faq" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_faq" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_stats" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_stats" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_group" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_group" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "snippets_blocks_newsletter" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "snippets_blocks_newsletter" DROP COLUMN "appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_hero_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_hero_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_features_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_features_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_cta_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_cta_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_rich_text_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_rich_text_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_hero_2_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_hero_2_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_features_2_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_features_2_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_cta_2_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_cta_2_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_rich_text_2_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_rich_text_2_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_logo_cloud_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_logo_cloud_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_pricing_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_pricing_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_testimonials_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_testimonials_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_faq_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_faq_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_stats_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_stats_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_group_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_group_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_form_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_form_appearance_padding_bottom";
  DROP TYPE "public"."enum_pages_blocks_newsletter_appearance_padding_top";
  DROP TYPE "public"."enum_pages_blocks_newsletter_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_hero_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_hero_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_features_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_features_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_cta_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_cta_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_hero_2_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_hero_2_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_features_2_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_features_2_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_cta_2_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_cta_2_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_2_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_2_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_logo_cloud_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_logo_cloud_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_pricing_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_pricing_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_faq_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_faq_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_stats_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_stats_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_group_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_group_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_form_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_form_appearance_padding_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_newsletter_appearance_padding_top";
  DROP TYPE "public"."enum__pages_v_blocks_newsletter_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_hero_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_hero_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_features_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_features_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_cta_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_cta_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_rich_text_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_rich_text_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_hero_2_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_hero_2_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_features_2_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_features_2_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_cta_2_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_cta_2_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_rich_text_2_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_rich_text_2_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_logo_cloud_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_logo_cloud_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_pricing_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_pricing_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_testimonials_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_testimonials_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_faq_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_faq_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_stats_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_stats_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_group_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_group_appearance_padding_bottom";
  DROP TYPE "public"."enum_snippets_blocks_newsletter_appearance_padding_top";
  DROP TYPE "public"."enum_snippets_blocks_newsletter_appearance_padding_bottom";`);
}
